### ISSUE TITLE
Logo doesn't work yet

### ISSUE THREAD

**Issue by bobbimanners** [bobbimanners/Applecorn#132]
With the latest Applecorn and the two Logo ROMs, I get a language signon message from each ROM and then a crash with the letter 'X' printed on the screen:

```
LOGO 1
LOGO 2
X
```
Need to debug this.

**Comment by bobbimanners** [comment]
@jgharston Can I remind you to take a look and see if you have Logo ROM disassembly.  Would like to get Logo going :)

**Comment by jgharston** [comment]
https://mdfs.net/System/ROMs/Graphics/LOGOv100.zip

**Comment by bobbimanners** [comment]
Awesome! Thanks :)

**Comment by bobbimanners** [comment]
Trace from MAME attached
[logo-trace.txt](https://github.com/bobbimanners/Applecorn/files/7532941/logo-trace.txt)
.

**Comment by bobbimanners** [comment]
From the trace, we can tell:

1) The LOGO.2 ROM is banked in.
2) The code winds up going here (from JGH's disassembly of LOGO ROM 2):
```
LDA #&58             :\ B585 A9 58       )X
.LB587
JSR OSWRCH           :\ B587 20 EE FF     n.
.LB58A
JMP LB58A            :\ B58A 4C 8A B5    L.5
```
This prints an 'X' and loops forever.

However I don't yet know why it is winding up here.

Something curious, in the MAME trace, the address appears different:
```
B276: jmp $0416
0416: ldy #$00
0418: lda ($06), y
041A: tay
041B: inc $06
041D: bne $0421
0421: ldx $be00, y
0424: stx $52
0426: ldx $bf00, y
0429: stx $53
042B: jmp ($0052)
B657: lda #$58                           Character 'X'
B659: jsr $ffee
FFEE: jmp ($020e)                        OSWRCH
E9A8: pha                                1
E9A9: phx                                2
E9AA: phy                                3
E9AB: jsr $d1e1                          5

```

$B659 in the trace corresponds to $B587 in the disassembly.  Why?

**Comment by bobbimanners** [comment]
Address offset is $D2 or 210 bytes.  Not a round number.

Also interesting that it arrives at the OSWRCH call through vector $52, from code running in aux at $042B, which is presumably code that has been written there by the LOGO rom?  Or I don't trust the addresses in the MAME trace.

**Comment by jgharston** [comment]
Ah, I see what's going wrong with LOGO.

It's talking directly to the ROM paging hardware on the BBC - which
doesn't exist on the Apple!

It starts off quite well using proper service calls to communicate
between the two parts of itself, then copies code to &0400 to
directly manipulate (non-existant) hardware!

All through the disassembly I was thinking "WTH????". It seems
really badly written - how come it needs 32K of code? I wrote a
LOGO program in 1K of BASIC! How come it builds the string
"FX163,241,Y" instead of just calling OSBYTE? etc. etc.

I had a look through the code to see if it would work with
OSBYTE &82 returning &0000 to indicate it was running on the
language processor - so with no access to the hardware.
However, that has the same problem as some other languages, it
takes that response as meaning that there is RAM all the way
up to &FFFF and so copies itself up into high memory at
&C000-&F000 - which isn't memory on the Apple, it's the I/O
space!

So, I think this version of LOGO will most likely not be workable
on the Apple.

-- 
J.G.Harston - ***@***.*** - mdfs.net/jgh

**Comment by jgharston** [comment]
On 14-11-2021 13:03, J.G.Harston wrote:
> All through the disassembly I was thinking "WTH????". It seems
> really badly written - how come it needs 32K of code? I wrote a
> LOGO program in 1K of BASIC! How come it builds the string
> "FX163,241,Y" instead of just calling OSBYTE? etc. etc.

I speculatively looked at a couple of other Acornsoft ROMs. They
*ALSO* have embedded strings "fx163,xxx,yyy" as well! Somebody
somewhere completely misunderstood the entire point of the
MOS API!

-- 
J.G.Harston - ***@***.*** - mdfs.net/jgh

**Comment by bobbimanners** [comment]
That is a shame, seems like Logo is a no-go then ;)

**Comment by jgharston** [comment]
There's at least two other versions of LOGO, could try them:
https://mdfs.net/System/ROMs/Graphics/

**Comment by bobbimanners** [comment]
I should give those a go.

Incidentally I tried AJS FORTAN the other day.  It starts up but I was unable to get it to do anything much.  Maybe I just don't know how to use it!

**Comment by bobbimanners** [comment]
Open Logo from the Open University seems to more-or-less work (as best as I can tell with no manual).

I put the 'L' ROM in slot 7 and the 'S' ROM in slot 8.  Doesn't start up if they are reversed.

**Comment by bobbimanners** [comment]
ACTLogo and CATLogo both appear to start.

ACTLogo switches to mode 6 or 7, even if I try to force mode 1 on startup.  So hard to tell how well it works.  The REPL is running though.

CATLogo can switch into mode 1 and does draw on the screen, but display is corrupt as though it is drawing outside screen bounds.  We need better clipping code because FDraw does not behave well when you give it co-ordinates out of range.  (Open Logo shows some of these issues too, but it is less severe.)

**Comment by bobbimanners** [comment]
This turns out to be the manual for ACT Logo aka Logotron.

**Comment by bobbimanners** [comment]
I am going to close this.  Acornsoft Logo is never going to work with Applecorn.  Open Logo from Open University is a possible alternative.  I am not a huge fan of Logo and we are focusing on Acornsoft languages for now.
