### ISSUE TITLE
UI to choose which ROM to load

### ISSUE THREAD

**Issue by bobbimanners** [bobbimanners/Applecorn#6]
Would be nice!

**Comment by jgharston** [comment]
I've written a stop-gap program LOADROM on the test.po disk that loads a ROM and enters it.

I've been trying to find if BRUN passes on the command line so you could do, for example:
BRUN APPLECORN COMOL.ROM

and it would see the COMOL.ROM on the command line and load that instead of the default ROM.

**Comment by bobbimanners** [comment]
ProDOS does stash the command line somewhere.  I wanna say $0280, but don't quote me on it.

cc65 uses that to support `argc` `*argv[]` semantics.

**Comment by bobbimanners** [comment]
Where do I find your test.po ?  That LOADROM thing sounds useful!

**Comment by jgharston** [comment]
LOADROM is on the test.po disk image in my repository, along with a load of other test programs.

**Comment by bobbimanners** [comment]
Implemented a simple ROM selection menu.  (New file MAIN.ROMMENU.S)
